#!/usr/bin/env python3
"""R6 ablation, the missing arm: +LLM-DDx scaffold (no KG, no bc).
Feed the reader the LLM-generated candidate concepts (the walker's seeds) as a plain differential
list — same 4-step skeleton as the walker reader — with NO graph expansion, NO scores, NO bc.

Isolates: how much of the MCQ gain is just handing the LLM its own differential, independent of KG?

Four-arm decomposition (all on 329, gpt-5.4-mini, same raw-retrieval family for C/D):
  A no-KG (PROMPT_NO_KG, 4-step, no evidence)        -> run here (arm A) for a clean common floor
  B +DDx scaffold (seeds as list, no KG/bc)          -> this script
  C +KG cos-only        = bench340_walker_BC0   82.98
  D +KG cos+bc (full)   = bench340_walker_fixABCmtS 83.89
"""
import json, re, sys
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
ROOT = Path(__file__).resolve().parent.parent; CACHE = ROOT/"cache"
sys.path.insert(0, str(ROOT/"scripts"))
from spectrum_textbook import call_llm

B = {x["uid"]: x for x in json.load(open(CACHE/"benchmark_bench329_clean.json"))}
SEEDS = json.load(open(CACHE/"bench340_seeds_multitype.json"))

PROMPT_NOKG = """You are an expert medical diagnostician. Solve the multiple-choice medical question by reasoning step by step.

Question:
{q}

Options:
{opts}

Think step by step:
1. Identify the key clinical findings, demographics, and duration in the case.
2. Enumerate your differential diagnosis (3-5 candidates) based on the presentation.
3. For each candidate, evaluate compatibility with the patient's symptom duration and other clinical features.
4. Rank the candidates and select the most likely diagnosis.

After your step-by-step reasoning (under 300 words), state your final answer as a single letter enclosed in <a></a> tags. Example: <a>C</a>."""

PROMPT_DDX = """You are an expert medical diagnostician. Solve the multiple-choice medical question by reasoning step by step.

Question:
{q}

Options:
{opts}

Candidate concepts generated by an LLM from the case vignette (NO external knowledge retrieval; the answer options were NOT used to generate these):
{ddx}

Think step by step:
1. Identify the key clinical findings, demographics, and duration in the case.
2. Enumerate your differential diagnosis (3-5 candidates) based on the presentation and the candidate concepts above.
3. For each candidate, evaluate compatibility with the patient's symptom duration and other clinical features.
4. Rank the candidates and select the most likely diagnosis.

After your step-by-step reasoning (under 300 words), state your final answer as a single letter enclosed in <a></a> tags. Example: <a>C</a>."""

def extract(raw):
    if not raw: return None
    m = re.search(r"<a>\s*([A-J])\s*</a>", raw, re.I)
    if m: return m.group(1).upper()
    m = re.search(r"\b(?:answer is|final answer[:\s]*)\**\(?([A-J])\)?", raw, re.I)
    return m.group(1).upper() if m else None

def opts_block(o): return "\n".join(f"  {k}. {v}" for k,v in sorted(o.items()))

def run_arm(name, make_prompt):
    def one(u):
        it=B[u]
        p=make_prompt(it)
        raw=call_llm(p, model="gpt-5.4-mini")
        pred=extract(raw)
        return {"uid":u,"gold":it["answer"],"predicted":pred,"is_correct":pred==it["answer"]}
    res=[]
    with ThreadPoolExecutor(max_workers=8) as ex:
        futs={ex.submit(one,u):u for u in B}
        for i,f in enumerate(as_completed(futs)):
            res.append(f.result())
            if (i+1)%80==0: print(f"  {name} {i+1}/{len(B)}",flush=True)
    c=sum(1 for r in res if r["is_correct"])
    json.dump({"metadata":{"arm":name,"model":"gpt-5.4-mini","n":len(res),"n_correct":c,
               "accuracy":100*c/len(res)},"results":res},
              open(CACHE/f"ablate_r6_{name}__gpt-5.4-mini.json","w"), indent=1)
    print(f"[{name}] {c}/{len(res)} = {100*c/len(res):.2f}%",flush=True)
    return 100*c/len(res)

def mk_nokg(it): return PROMPT_NOKG.format(q=it["question"], opts=opts_block(it["options"]))
def mk_ddx(it):
    seeds=(SEEDS.get(it["uid"]) or {}).get("seeds",[])
    ddx="\n".join(f"- {s}" for s in seeds) if seeds else "(none)"
    return PROMPT_DDX.format(q=it["question"], opts=opts_block(it["options"]), ddx=ddx)

print("=== R6 four-arm decomposition (329, gpt-5.4-mini) ===")
a=run_arm("A_nokg", mk_nokg)
b=run_arm("B_ddx_scaffold", mk_ddx)
print(f"\nArm A no-KG            : {a:.2f}%")
print(f"Arm B +DDx scaffold   : {b:.2f}%   (Δ from A = {b-a:+.2f})")
print(f"Arm C +KG cos-only    : 82.98%   (bench340_walker_BC0, Δ from B = {82.98-b:+.2f})")
print(f"Arm D +KG cos+bc      : 83.89%   (bench340_walker_fixABCmtS, Δ from C = +0.91)")
